<a href="https://colab.research.google.com/github/DiegoYanezFlores/Programacion-Funcional-Computacion-Analitica/blob/main/PARCIAL_1_CUADERNO_DE_TEORIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CLASE 1: Sintaxis Base y Colecciones (El insumo de los datos)

Bienvenidos a Programación Funcional y Computación Científica!

Antes de construir algoritmos matemáticos complejos o bots de inversión, debemos entender nuestra materia prima: los datos. En la vida real, la información financiera no llega de a un número a la vez; llega en bloques masivos a través de internet (APIs).

Para poder manipular esta información, Python utiliza "contenedores" nativos. Hoy dominaremos los dos más importantes:

## 1. Variables y Tipos de Datos Base


A diferencia de otros lenguajes, Python es de "tipado dinámico". No necesitas decirle qué tipo de dato vas a guardar, él lo adivina. En nuestro contexto financiero usaremos:
* **String (`str`):** Cadenas de texto, como el símbolo de una moneda ("BTC", "USD").
* **Float (`float`):** Números decimales, vitales para precios y tasas de interés (65000.50).
* **Integer (`int`):** Números enteros, usados para contar volumen de transacciones (1500).
* **Boolean (`bool`):** Verdadero o Falso (`True` / `False`), útiles para saber si un mercado está abierto o cerrado.

## 2. Colecciones: Listas y Diccionarios


Cuando necesitamos agrupar miles de variables, usamos colecciones:
* **Listas (`[]`):** Son secuencias ordenadas. Piensa en ellas como una fila de casilleros. Empezamos a contar desde el casillero `0`.
* **Diccionarios (`{}`):** Funcionan con **llaves y valores** (Key-Value). En lugar de buscar por la posición numérica, buscas por el "nombre" de la llave (ej. `precio`).

> **💡 El Secreto del Analista de Datos:** En la Unidad 3 nos conectaremos a la API del Banco Central. Las APIs envían la información en un formato universal llamado **JSON**. Afortunadamente, un JSON en Python se traduce exactamente como un **Diccionario anidado** (un diccionario que contiene listas, que a su vez contienen más diccionarios). ¡Aprender a navegar esta estructura es el primer paso para dominar los datos!

In [ ]:
# ========================================================
# 1. VARIABLES Y TIPOS DE DATOS EN UN CONTEXTO FINANCIERO
# ========================================================
ticker = "BTC/USD"       # str (Texto)
precio_actual = 65430.50 # float (Decimal)
mercado_abierto = True   # bool (Booleano)

print("--- 1. Variables Base ---")
print(f"Moneda: {ticker} | Precio: ${precio_actual} | Tipo de dato del precio: {type(precio_actual)}")

# ========================================================
# 2. LISTAS (Ordenadas por Índice)
# ========================================================
# Los índices en Python empiezan en 0.
# 0 = Lunes, 1 = Martes, 2 = Miércoles...
precios_semana = [64000.0, 64500.5, 65000.0, 64800.0, 65430.5]

print("\n--- 2. Navegando Listas ---")
print(f"El precio del día miércoles (índice 2) fue: ${precios_semana[2]}")

# ========================================================
# 3. DICCIONARIOS ANIDADOS (Simulando un JSON de una API)
# ========================================================
# Así es exactamente como los bancos y exchanges envían los datos por internet.
respuesta_api = {
    "status": "OK",
    "fecha": "2024-05-15",
    "activos": [
        {"nombre": "Bitcoin", "simbolo": "BTC", "precio": 65430.50, "riesgo": "Alto"},
        {"nombre": "Ethereum", "simbolo": "ETH", "precio": 3200.75, "riesgo": "Alto"},
        {"nombre": "Oro", "simbolo": "XAU", "precio": 2300.00, "riesgo": "Bajo"}
    ]
}

print("\n--- 3. Extrayendo datos de un JSON simulado ---")
# RETO: ¿Cómo extraemos el precio del Ethereum paso a paso?
# Paso 1: Entramos al diccionario principal usando la llave 'activos'
# Paso 2: Como 'activos' es una lista, seleccionamos el Ethereum usando el índice [1]
# Paso 3: Ahora que estamos dentro del diccionario de Ethereum, pedimos la llave 'precio'

precio_extraido = respuesta_api["activos"][1]["precio"]
print(f"El precio extraído de ETH es: ${precio_extraido}")

# Recorriendo la colección completa con un bucle simple
print("\nResumen de mercado:")
for moneda in respuesta_api["activos"]:
    print(f" -> {moneda['simbolo']} cotiza a ${moneda['precio']}")

--- 1. Variables Base ---
Moneda: BTC/USD | Precio: $65430.5 | Tipo de dato del precio: <class 'float'>

--- 2. Navegando Listas ---
El precio del día miércoles (índice 2) fue: $65000.0

--- 3. Extrayendo datos de un JSON simulado ---
El precio extraído de ETH es: $3200.75

Resumen de mercado:
 -> BTC cotiza a $65430.5
 -> ETH cotiza a $3200.75
 -> XAU cotiza a $2300.0


### Análisis del Código: ¿Qué acaba de pasar?

Si es tu primera vez viendo este código, vamos a desarmarlo pieza por pieza para entender la lógica de Python:

**1. El secreto de las `f-strings` y la función `type()`**
* Notarás que en los `print` ponemos una letra **`f`** justo antes de las comillas: `f"Moneda: {ticker}"`. Esto se llama *F-string* (Formatted string). Nos permite inyectar variables directamente dentro del texto usando llaves `{}`. Es la forma más profesional y limpia de imprimir resultados.
* La función `type(precio_actual)` es el escáner de Python. Al pasarle una variable, nos responde qué tipo de dato hay dentro. En nuestro caso, nos confirmó que `65430.50` pertenece a la clase `<float>` (decimal).

**2. Listas y la regla del "Índice Cero"**
* En la lista `precios_semana = [64000.0, 64500.5, 65000.0...]`, pedimos imprimir el índice `[2]`.
* **Regla de oro en programación:** Las computadoras no empiezan a contar desde el 1, empiezan desde el **0**.
    * Índice 0 = 64000.0 (Lunes)
    * Índice 1 = 64500.5 (Martes)
    * **Índice 2 = 65000.0 (Miércoles)**

**3. Diseccionando el JSON (Diccionario Anidado)**
La línea `precio_extraido = respuesta_api["activos"][1]["precio"]` parece un trabalenguas, pero es solo un mapa del tesoro lógico. Se lee de izquierda a derecha:
* `respuesta_api`: "Entra al diccionario principal".
* `["activos"]`: "Abre la puerta llamada *activos*". Al abrirla, Python encuentra una Lista `[ ]`.
* `[1]`: "De esa lista, dame el elemento en la posición 1" (Recuerda: 0 es Bitcoin, **1 es Ethereum**). Al sacarlo, Python ve que es otro diccionario.
* `["precio"]`: "De este nuevo diccionario de Ethereum, dame el valor guardado bajo la llave *precio*".

**4. El Bucle For (Automatizando la lectura)**
En las últimas líneas usamos: `for moneda in respuesta_api["activos"]:`
* Esto le dice a Python: "Ve a la lista de *activos*. Por cada elemento que encuentres allí, bautízalo temporalmente con el nombre `moneda`, entra, saca su símbolo y su precio, imprímelo, y repite el proceso hasta que se acabe la lista". ¡Acabamos de automatizar la lectura de un JSON!

# CLASE 2: Programación Defensiva y Funciones Base

## Funciones Base

### Concepto 1: Funciones (`def`) - Tu fábrica de código
Imagina que necesitas calcular el impuesto de 1,000 precios distintos. Escribir la fórmula matemática 1,000 veces es ineficiente y propenso a errores.

Una **función** es como construir una máquina especializada en una fábrica:
1. La construyes una sola vez.
2. Le entregas materia prima (**Parámetros** o Entradas).
3. La máquina hace su trabajo interno.
4. Te devuelve un producto terminado (**Return** o Salida).

In [ ]:
# 1. CONSTRUIMOS LA MÁQUINA (Usamos la palabra reservada 'def')
def calcular_ganancia_neta(ingreso_bruto, costo_operativo):
    """Calcula la ganancia después de restar los costos y un 15% de impuestos."""

    ganancia_bruta = ingreso_bruto - costo_operativo
    impuestos = ganancia_bruta * 0.15
    ganancia_neta = ganancia_bruta - impuestos

    # El 'return' es la cinta transportadora que expulsa el resultado hacia afuera
    return ganancia_neta


# 2. USAMOS LA MÁQUINA (Llamamos a la función)
empresa_A = calcular_ganancia_neta(10000, 2000)
empresa_B = calcular_ganancia_neta(50000, 15000)

print(f"Ganancia limpia Empresa A: ${empresa_A}")
print(f"Ganancia limpia Empresa B: ${empresa_B}")

Ganancia limpia Empresa A: $6800.0
Ganancia limpia Empresa B: $29750.0


### Concepto 2: El "Scope" (Ámbito) y la regla de la Caja Negra

Este es uno de los conceptos más importantes para entender la Programación Funcional más adelante.
Una función es una **caja negra** hermética. Lo que pasa en Las Vegas, se queda en Las Vegas.

* **Variables Locales:** Cualquier variable que crees *dentro* de una función, nace y muere dentro de ella. El resto de tu programa no sabe que existe.
* **El error común:** Olvidar poner el `return`. Si no pones `return`, la máquina se traga tus datos, hace el cálculo y no te devuelve nada (devuelve un valor vacío llamado `None`).

In [ ]:
# Variable Global (Existe en todo el programa, todos pueden verla)
tasa_conversion_global = 0.92  # Dólar a Euro

def convertir_dolares_a_euros(monto_dolares):
    # 'euros_calculados' es una Variable LOCAL.
    # Solo existe mientras esta función está trabajando.
    euros_calculados = monto_dolares * tasa_conversion_global

    return euros_calculados

# Ejecutamos la función
billetera_dolares = 500
billetera_euros = convertir_dolares_a_euros(billetera_dolares)

print(f"Tus ${billetera_dolares} USD equivalen a €{billetera_euros} EUR")

# ⚠️ LA PRUEBA DEL SCOPE:
# Si descomentas (le quitas el #) a la siguiente línea y ejecutas la celda,
# Python te dará un error (NameError), porque 'euros_calculados' ya murió
# y no existe fuera de la función.

# print(euros_calculados)

Tus $500 USD equivalen a €460.0 EUR


### La transición hacia la Programación Defensiva

Ahora que sabemos cómo construir una "máquina" (Función) que aísla nuestro código, ¿qué pasa si el usuario introduce un texto como `"Mil dólares"` en lugar del número `1000`? **Nuestra máquina se romperá.**

Para evitar que la máquina se queme, debemos instalarle un "escudo protector" en su interior. A esto le llamamos el bloque **Try / Except**.

## Programación Defensiva: El arte de prever el caos


En la Clase 1 vimos cómo navegar datos, pero asumimos que los datos eran "perfectos". En el mundo real (y especialmente en computación científica), los datos son **sucios**: una API puede enviarte un texto donde debería haber un número, o un valor nulo (`None`) porque un sensor falló.

En el mundo real del análisis de datos, la información casi nunca llega limpia. Las APIs fallan, los sensores se apagan y los humanos cometen errores de tipeo. Si no preparamos nuestro código para el caos, colapsará.

Para evitar esto, utilizaremos dos herramientas fundamentales: las **Funciones** y el bloque **Try/Except**.


### Concepto 1: Funciones (`def`) - Encapsulando la lógica


Imagina que una función es una "máquina procesadora". Tú le entregas materia prima (parámetros de entrada), la máquina realiza un trabajo interno aislado, y al final expulsa un producto terminado (`return`).
* **Ventaja:** En lugar de escribir el mismo cálculo 100 veces, lo escribes una sola vez dentro de la máquina y simplemente la llamas cuando la necesites.

In [ ]:
# Definimos nuestra función (La Máquina)
def calcular_ganancia(inversion_inicial, tasa_crecimiento):
    # Lógica interna (Aislada del resto del programa)
    ganancia = inversion_inicial * tasa_crecimiento
    return ganancia

# Usamos la máquina con diferentes datos
cliente_1 = calcular_ganancia(1000, 0.05)
cliente_2 = calcular_ganancia(5000, 0.10)

print(f"Ganancia Cliente 1: ${cliente_1}")
print(f"Ganancia Cliente 2: ${cliente_2}")

Ganancia Cliente 1: $50.0
Ganancia Cliente 2: $500.0


### Concepto 2: Programación Defensiva (`try / except`)

¿Qué pasaría si al intentar calcular una ganancia, la base de datos nos envía el texto `"N/A"` en lugar del número `1000`? **El programa explotaría y se detendría por completo.**

Aquí entra la Programación Defensiva. El bloque `try / except` funciona como una red de seguridad de un trapecista:
* **`try` (Intentar):** Le decimos a Python "intenta ejecutar esta línea riesgosa".
* **`except` (Excepción):** Le decimos "Si el intento falla y ocurre un error, ¡no te apagues! Ejecuta este plan B".

In [ ]:
# Un dato corrupto que vino de internet
precio_corrupto = "Sin_Datos"

print("Intentando procesar el dato...")

try:
    # Intentamos convertir la palabra "Sin_Datos" a un número decimal
    precio_decimal = float(precio_corrupto)
    print(f"Éxito. El precio es {precio_decimal}")

except ValueError:
    # Como Python no puede convertir letras a números, da un "ValueError".
    # En lugar de colapsar, cae en esta red de seguridad.
    print("⚠️ ALERTA: El dato no es un número válido.")
    precio_decimal = 0.0  # Asignamos un valor por defecto para no arruinar la base de datos

print(f"El programa sigue funcionando tranquilamente. Valor final guardado: {precio_decimal}")

Intentando procesar el dato...
⚠️ ALERTA: El dato no es un número válido.
El programa sigue funcionando tranquilamente. Valor final guardado: 0.0


### Uniendo Todo: El Pipeline Defensivo
Ahora vamos a combinar ambos conceptos. Crearemos una **Función** que tenga por dentro una **Red de Seguridad (Try/Except)**.

Luego, haremos pasar una lista entera de datos sucios financieros por esta máquina. La máquina limpiará los datos buenos y transformará los errores en ceros, permitiendo que el análisis fluya sin interrupciones.

# 1. Creamos la función con escudo protector
def limpiar_precio_defensivo(dato_crudo):
    """
    Intenta convertir cualquier dato a float.
    Si hay error de valor (texto) o de tipo (None), devuelve 0.0
    """
    try:
        return float(dato_crudo)
    except (ValueError, TypeError):
        return 0.0

# 2. Simulamos una lista masiva de datos con errores
datos_api = ["105.50", "106.20", "N/A", "110.00", None, "108.50", "Error_404"]

# 3. Nuestro carrito de compras para los datos procesados
precios_seguros = []

# 4. Procesamos la lista (El Pipeline)
print("Iniciando procesamiento de datos masivos...\n")

for dato in datos_api:
    # Usamos nuestra función para limpiar cada elemento uno por uno
    precio_limpio = limpiar_precio_defensivo(dato)
    
    # Filtramos: Solo guardamos los que superaron la limpieza (mayores a 0)
    if precio_limpio > 0:
        precios_seguros.append(precio_limpio)
    else:
        print(f" -> Dato descartado por corrupción: '{dato}'")

print(f"\n✅ Procesamiento terminado. Lista original tenía {len(datos_api)} elementos.")
print(f"✅ Lista final segura para cálculos matemáticos: {precios_seguros}")

# CLASE 3: El Salto de Paradigma: Imperativo vs. Funcional y Recursividad

Hasta ahora, hemos programado como si fuéramos gerentes micro-gestionando a un empleado. Le hemos dicho a la computadora **CÓMO** hacer cada pequeño paso (crea una variable, haz un bucle, suma uno, guárdalo...). A esto se le llama **Paradigma Imperativo**.

En la Inteligencia Artificial y la Computación Científica, esto es ineficiente. Aquí usamos el **Paradigma Funcional**.
En lugar de dar instrucciones paso a paso, declaramos **QUÉ** queremos calcular mediante expresiones matemáticas puras.

* **Imperativo:** Usa variables que cambian constantemente (estado) y bucles (`for`, `while`).
* **Funcional:** No cambia las variables una vez creadas (inmutabilidad) y reemplaza los bucles con **Recursividad**.

In [ ]:
# ==========================================================
# EL ENFOQUE IMPERATIVO (Microgestión y Estado cambiante)
# ==========================================================
# Queremos sumar los números del 1 al 5.
suma_total = 0                  # 1. Creamos un "estado" inicial
for numero in [1, 2, 3, 4, 5]:  # 2. Hacemos un bucle
    suma_total += numero        # 3. Mutamos (cambiamos) la variable constantemente

print(f"Suma Imperativa: {suma_total}")

# ==========================================================
# EL ENFOQUE FUNCIONAL (Matemáticas Puras)
# ==========================================================
# No creamos variables temporales, no hacemos bucles, no mutamos nada.
# Usamos las funciones integradas nativas de Python que operan sobre la colección entera.

numeros = [1, 2, 3, 4, 5]
resultado_funcional = sum(numeros)

print(f"Suma Funcional: {resultado_funcional}")

### Otro ejemplo: Buscando la aguja en el pajar

Imagina que queremos encontrar el precio más alto histórico de una acción.
* En el **enfoque imperativo**, crearíamos una variable temporal llamada `maximo_actual`, revisaríamos cada precio uno por uno y la actualizaríamos si encontramos uno mayor. ¡Mucho trabajo manual!
* En el **enfoque funcional**, simplemente le decimos a Python: "Dame el máximo".

In [ ]:
precios_historicos = [150.5, 155.0, 149.0, 160.2, 158.0]

# --- ENFOQUE IMPERATIVO ---
precio_maximo = 0.0
for precio in precios_historicos:
    if precio > precio_maximo:
        precio_maximo = precio  # Mutando el estado constantemente

print(f"Máximo (Imperativo): ${precio_maximo}")

# --- ENFOQUE FUNCIONAL ---
# No mutamos nada, usamos funciones declarativas nativas.
maximo_funcional = max(precios_historicos)

print(f"Máximo (Funcional): ${maximo_funcional}")

## El Salto de Paradigma (Recursividad y Composición)

Hasta ahora, hemos usado bucles (`for`) para repetir tareas. Pero en el paradigma funcional y en las matemáticas puras, los bucles no existen. En su lugar, usamos la **Recursividad**.

### 1. La Recursividad: El arte de llamarse a sí mismo

Imaginen una Matrioshka (una muñeca rusa). Quieren saber si hay un dulce escondido en la muñeca más pequeña. ¿Qué hacen? Abren la muñeca. Si hay otra muñeca adentro, aplican *exactamente la misma acción*: la abren. Hacen esto una y otra vez hasta llegar a la última muñeca, que ya no se abre. Ahí encuentran el dulce.

Eso, señores, es la recursividad: **una función que se llama a sí misma para resolver una versión más pequeña del mismo problema.**

Toda función recursiva DEBE tener dos reglas inquebrantables:
1. **El Caso Base (El freno de mano):** Es la condición que le dice a la función: *"¡Detente! Ya llegaste al fondo, no te llames más a ti misma"*. (Es la muñeca rusa más pequeña. Sin esto, el programa colapsaría en un ciclo infinito).
2. **El Caso Recursivo (El paso al vacío):** Es la parte donde la función se llama a sí misma, pero enviando un pedazo de datos *más pequeño* que el original.

**El ejemplo matemático perfecto:**
Para que vean que esto es pura ciencia, veamos cómo se define el factorial de un número (por ejemplo, $5! = 5 \times 4 \times 3 \times 2 \times 1$). En matemáticas, no se define con un bucle, se define de forma puramente recursiva:
$$n! = n \times (n-1)!$$

Pero necesitamos un **Caso Base**, o contaríamos hacia los negativos infinitamente:
$$0! = 1$$

In [ ]:
# ==========================================================
# RECURSIVIDAD: Calculando el Factorial
# ==========================================================

def calcular_factorial(n):
    # 1. EL CASO BASE (El freno de mano matemático)
    if n == 0:
        return 1  # 0! siempre es 1

    # 2. EL CASO RECURSIVO (La función se llama a sí misma)
    # Ejemplo si n es 5: Retorna 5 * calcular_factorial(4)
    return n * calcular_factorial(n - 1)

# Prueba del algoritmo
numero = 5
resultado = calcular_factorial(numero)

print(f"El cálculo puro de {numero}! es: {resultado}")

### 2. Composición Funcional: El ADN de la Inteligencia Artificial



Si la recursividad es una función llamándose a sí misma, la **Composición Funcional** es el arte matemático de encadenar *distintas* funciones puras y especialistas.

En la Inteligencia Artificial, rara vez una sola función hace todo el trabajo. En lugar de escribir una función monolítica gigante y frágil, creamos funciones pequeñas. La salida de una se convierte instantáneamente en la entrada de la siguiente.

Matemáticamente, si tenemos una función $g(x)$ que limpia un dato, y otra función $f(x)$ que lo multiplica, la composición se define como:
$$h(x) = f(g(x))$$
*(Se lee: "f de g de x")*

**¿Por qué importa esto en IA y Computación Científica?**
Porque una Red Neuronal Profunda (Deep Learning) no es más que un gigantesco **Grafo Computacional** de funciones compuestas. Los datos entran por una capa (que es una función matemática), se transforman, y su resultado pasa inmediatamente a la siguiente capa.

In [ ]:
# ==========================================================
# COMPOSICIÓN FUNCIONAL: h(x) = f(g(x))
# ==========================================================

# Función g(x): Aisla la lógica de limpieza (Usando lo aprendido en la Clase 2)
def limpiar_precio_g(precio_crudo):
    """Convierte texto a número. Si falla, devuelve 0."""
    try:
        return float(precio_crudo)
    except:
        return 0.0

# Función f(x): Aisla la lógica matemática (Aplicar 15% de impuesto)
def aplicar_impuesto_f(precio_limpio):
    return precio_limpio * 1.15

# --- El Grafo Computacional ---
# Simulamos un dato sucio que viene de internet
dato_internet = "100.00"

# En lugar de crear variables temporales, COMPONEMOS las funciones: f(g(x))
# La salida de limpiar_precio_g se inyecta directamente dentro de aplicar_impuesto_f
precio_final_h = aplicar_impuesto_f(limpiar_precio_g(dato_internet))

print(f"Dato original: '{dato_internet}'")
print(f"Resultado tras pasar por el pipeline f(g(x)): ${precio_final_h:.2f}")

# CLASE 4: La Tríada Funcional (lambda, map, filter) y List Comprehensions

##  1. LAMBDA

Una lambda no es más que una función desechable. Es como escribir una nota en un Post-it: la usas rápido y la tiras. No necesitas ponerle un nombre formal con def. Solo pones qué recibe y qué devuelve.


In [ ]:
# La forma aburrida y larga (con 'def'):
def sumar_diez(numero):
    return numero + 10

print(sumar_diez(5)) # Da 15

# RETO PARA LOS ESTUDIANTES:
# Creen exactamente lo mismo usando 'lambda' en una sola línea.

sumar = lambda numero: numero + 10

print(sumar(7))

15
17


## 2. Filter (El Guardia de Seguridad)

Ahora que sabemos hacer 'post-its', vamos a dárselos a un guardia de seguridad. *filter* se para en la puerta de un antro o discoteca. Mira tu lista de datos y decide quién pasa y quién no, basándose en la regla de tu lambda.

In [ ]:
edades = [15, 20, 12, 35, 17, 22]

# RETO PARA LOS ESTUDIANTES:
# Usen 'filter' y una 'lambda' para dejar pasar SOLO a los mayores o iguales a 18.

mayores = filter(lambda e : e >= 18, edades)

print(mayores) # [20, 35, 22]

## 3. Map (La Maquina Transformadora)

Olvídense de filtrar. Ahora imaginemos que todos pasan, pero pasan por una máquina de rayos X que los transforma. map agarra CADA elemento de tu lista y le hace exactamente la misma modificación a todos, sin excepciones.

In [ ]:
precios_sin_iva = [100, 200, 50]

# RETO PARA LOS ESTUDIANTES:
# Ustedes son el gobierno. Usen 'map' y una 'lambda' para agregarle
# un impuesto de 10 dólares a CADA producto.

pvp = map(lambda p : p + 10, precios_sin_iva)

print(list(pvp))


[110, 210, 60]


## 4. List (el boton de imprimir / materializar)

Python preparó la máquina, pero no la ha encendido. list() es el botón rojo de encendido que obliga a la máquina a escupir los datos reales en una lista que podamos leer.

Caso contrario vamos a ver errores de tipo "Object"

In [ ]:
# DE EJERCICOS ANTERIORES 2 Y 3

print(list(mayores))
print(list(pvp))

# EJERCICO NOMBRES
nombres = ["ana", "pedro", "juan"]
nombres_mayusculas = map(lambda n: n.upper(), nombres)

print(list(nombres_mayusculas))

[20, 35, 22]
[]
['ANA', 'PEDRO', 'JUAN']


In [ ]:
calificaciones = [40, 90, 50, 85, 100]

# 1. filter: Deja pasar solo a los que tienen 50 o más (los que no están tan mal)
# 2. map: A los que pasaron, súmales 5 puntos de "bono de buen comportamiento"
# 3. list: Muéstrame la lista final de los afortunados

resultado = list (
  map ( lambda x : x + 5 ,
      filter(lambda x : x >= 50, calificaciones))
)

print (resultado)

[95, 55, 90, 105]


## 5. List Comprehensions - La navaja suiza de Python

Ya aprendimos a usar `map` y `filter`. Son herramientas poderosas, pero a veces la sintaxis de `lambda` y los paréntesis se vuelve confusa.

Las **List Comprehensions** son una forma abreviada de crear listas nuevas a partir de otras. Su estructura básica es:
`[ transformación FOR elemento IN lista_original IF condición ]`

Es como leer una oración en inglés: "Haz esto para cada elemento en esta lista si se cumple aquello".
* **Es más rápido:** Python las procesa de forma más eficiente que un bucle `for` tradicional.
* **Es más limpio:** Lo que antes tomaba 5 líneas de código, ahora toma una.

In [ ]:
# Tenemos una lista de precios de activos financieros
precios = [100, 250, 400, 50, 150, 300]

# OBJETIVO: Queremos una lista con el 10% de impuesto aplicado,
# pero SOLO para los precios mayores a 200.

# 1. FORMA TRADICIONAL (Mucho código)
filtrados_old = []
for p in precios:
    if p > 200:
        filtrados_old.append(p * 1.10)

# 2. FORMA MODERNA: LIST COMPREHENSION (Elegante)
# [ (Transformación) | (Bucle) | (Filtro) ]
precios_con_impuesto = [p * 1.10 for p in precios if p > 200]

print(f"Lista original: {precios}")
print(f"Resultado con List Comprehension: {precios_con_impuesto}")

# Otro ejemplo: Limpiar espacios en blanco de una lista de nombres de acciones
acciones = ["  btc  ", " eth ", "  dot"]
acciones_limpias = [a.strip().upper() for a in acciones]

print(f"\nAcciones normalizadas: {acciones_limpias}")

### 💡 ¿Cuándo usar cada una?

* Usa **List Comprehensions** el 90% de las veces por su legibilidad.
* Usa **map/filter** cuando ya tienes funciones pre-definidas muy complejas que quieres aplicar directamente.
* Usa **reduce** solo cuando necesites "aplastar" toda una lista hasta convertirla en un solo valor (como una suma total o un aplanador de archivos).

# CLASE 5: Proyecto de Unidad: El Grafo Computacional (Pipeline)

Hemos llegado a la culminación de la Unidad 1. Hasta ahora tenemos funciones que limpian errores (Clase 2), sabemos hacer recursividad (Clase 3) y dominamos herramientas como `map` y `filter` (Clase 4).

Es hora de ensamblar nuestro **Bot Analítico**. En la industria, a esto se le llama construir un **Pipeline de Datos** (o Grafo Computacional).

### ¿Qué es un Pipeline?
Imagina una fábrica de autos (línea de ensamblaje):
1. **Estación 1:** Ensambla el chasis.
2. **Estación 2:** Pone el motor.
3. **Estación 3:** Pinta el auto.

En programación funcional, las "estaciones" son nuestras **funciones puras**, y la "cinta transportadora" que pasa el auto de una estación a otra es nuestra función `reduce`. El dato entra sucio por un extremo, atraviesa las tuberías (funciones), y sale procesado por el otro.

In [ ]:
# ==========================================================
# PASO 1: DEFINIR LAS ESTACIONES DE TRABAJO (Funciones Puras)
# ==========================================================
# Cada función hace UNA sola cosa, muy bien hecha.

# Estación 1: Filtro de seguridad (Quita números negativos)
def validar_precio(precio):
    return max(0, precio)  # Si es negativo, devuelve 0

# Estación 2: Lógica de negocio (Aplica comisión del Broker 5%)
def cobrar_comision(precio):
    return precio * 0.95

# Estación 3: Formateo final (Lo convierte en texto legible)
def formatear_salida(precio):
    return f"${precio:.2f} USD"

print("✅ Estaciones de trabajo construidas y listas.")

### La Cinta Transportadora: Encadenando funciones con `reduce`

Para no escribir `formatear_salida(cobrar_comision(validar_precio(x)))` (lo cual es muy feo y difícil de leer), vamos a usar `reduce` de la librería `functools`.

`reduce` toma una lista de elementos y los "comprime" aplicando una función. Nosotros lo usaremos para comprimir **nuestra lista de funciones** en una sola **Súper Función**.

In [ ]:
from functools import reduce

# ==========================================================
# PASO 2: CONSTRUIR LA CINTA TRANSPORTADORA
# ==========================================================

# Esta es la "Máquina que hace máquinas".
# Toma muchas funciones y empata la salida de una con la entrada de la siguiente.
def componer_pipeline(*funciones):
    return reduce(lambda f, g: lambda x: g(f(x)), funciones)

# Ensamblamos nuestro Pipeline uniendo las 3 estaciones
procesar_activo = componer_pipeline(validar_precio, cobrar_comision, formatear_salida)

# Probamos nuestra mega-función con un solo dato
dato_prueba = 100
resultado = procesar_activo(dato_prueba)

print(f"El dato ingresó como {dato_prueba} y salió del pipeline como {resultado}")

## Pureza y Transparencia Referencial en la Ciencia de Datos

Estos dos términos suenan intimidantes, pero son sus mejores amigos para evitar dolores de cabeza.

* Función Pura: Es una función que, si le das la misma entrada, siempre te dará
la misma salida. Además, no tiene efectos secundarios (no modifica variables globales, no escribe en bases de datos inesperadas, no altera el input original).

* Transparencia Referencial: Es la propiedad de poder reemplazar una llamada a una función directamente por su resultado, sin que el programa cambie su comportamiento.

¿Por qué importa en Ciencia de Datos? ¡Por la reproducibilidad! Si tu función para normalizar datos depende de una variable global que cambió sin que te dieras cuenta, tu modelo de Machine Learning dará resultados diferentes cada vez que lo entrenes. Eso es una pesadilla científica.

In [ ]:
# QUE NO HACER

dataset_global = [1, 2, 3]

def agregar_bias_impuro(bias):
    # ¡Alerta de efecto secundario! Modificando el dataset original
    for i in range(len(dataset_global)):
        dataset_global[i] += bias
    return dataset_global

print(agregar_bias_impuro(5)) # [6, 7, 8]
print(agregar_bias_impuro(5)) # [11, 12, 13] -> ¡La misma llamada dio un resultado distinto!

[6, 7, 8]
[11, 12, 13]


In [ ]:
# QUE SI HACER

def agregar_bias_puro(dataset, bias):
    # Retorna un NUEVO dataset, no toca el original
    return [x + bias for x in dataset]

datos = [1, 2, 3]
print(agregar_bias_puro(datos, 5)) # [6, 7, 8]
print(agregar_bias_puro(datos, 5)) # [6, 7, 8] -> ¡Predecible y confiable!
print(datos) # [1, 2, 3] -> El dato original está a salvo.


[6, 7, 8]
[6, 7, 8]
[1, 2, 3]


In [ ]:
dataset_ventas_original = [10, 20, 30]

def escalar_datos_puro(datos, multiplicador):
    # En lugar de modificar la lista original, CREAMOS UNA NUEVA.
    # Usamos una "List Comprehension" (o podríamos usar map!)
    nuevos_datos = [numero * multiplicador for numero in datos]
    return nuevos_datos

# Día 1: Entrenamos
print("Día 1:", escalar_datos_puro(dataset_ventas_original, 2)) # [20, 40, 60]

# Día 2: Verificamos
print("Día 2:", escalar_datos_puro(dataset_ventas_original, 2)) # [20, 40, 60]

# ¿Y nuestro dataset original?
print("Original:", dataset_ventas_original) # [10, 20, 30] -> ¡Intacto!

Día 1: [20, 40, 60]
Día 2: [20, 40, 60]
Original: [10, 20, 30]


## Construyendo nuestro primer Grafo Computacional (Pipeline)



Vamos a llevar la teoría a la práctica. En lugar de crear un tanque gigante de código, vamos a crear tres "filtros" independientes (funciones puras).

Luego, usaremos el poder de las matemáticas y la función `reduce` para "soldar" estos filtros y crear una tubería continua. Matemáticamente, estamos haciendo la composición $h(x) = f(g(x))$.

**Reglas de este taller:**
* No usaremos variables intermedias para guardar el estado del dato.
* Todo será elaborado de forma declarativa.

In [ ]:
from functools import reduce

# 1. Nuestros "Filtros" o "Capas" (Funciones puras, hacen solo 1 cosa)
limpiar_ruido = lambda x: max(0, x)      # Si el número es negativo, lo vuelve 0
aplicar_peso = lambda x: x * 2         # Simula el peso de una neurona
sumar_sesgo = lambda x: x + 1.2          # Simula el bias de una neurona

# 2. La Máquina Fusionadora (El Pegamento Matemático)
# Toma una lista de funciones y las empata una dentro de otra: g(f(x))
def componer_pipeline(*funciones):
    return reduce(lambda f, g: lambda x: g(f(x)), funciones)

# 3. Construimos el Grafo (Unimos los tubos)
# red_neuronal ahora es UNA SOLA función que contiene a las tres.
red_neuronal = componer_pipeline(limpiar_ruido, aplicar_peso, sumar_sesgo)

# 4. Abrimos la llave del agua (El dato entra a la tubería)
dato_entrada = 5
resultado = red_neuronal(dato_entrada)

print(f"Dato de entrada crudo: {dato_entrada}")
print(f"Dato procesado por el grafo: {resultado}")

Dato de entrada crudo: 5
Dato procesado por el grafo: 11.2


### Aplanando Estructuras Complejas (Sin mutar datos)



Ahora llevemos esto al Big Data y la IA. Imagina que un sensor envía lecturas agrupadas por zonas, pero la estructura se corrompió y las listas están anidadas de forma caótica. Nuestra red neuronal necesita una lista perfectamente plana.

**Reglas de la Programación Funcional Pura:**
* Prohibido usar `.append()` o `.extend()` (mutan la lista original).
* Prohibido usar bucles `for` o variables temporales.
* **Nuestra herramienta:** Usaremos la concatenación pura de listas (`[1] + [2, 3] = [1, 2, 3]`) y la función de orden superior `reduce`.

In [ ]:
from functools import reduce

# Nuestro dataset caótico
datos_anidados = [10, [20, 30], [[40]], 50, [60, [70, 80]]]

def aplanar_arbol(nodo):

  # 1. CASO BASE: Si el 'nodo' no es una lista, es un número suelto (una hoja).
  # Lo envolvemos en una lista para poder concatenarlo matemáticamente después.

  if not isinstance(nodo, list):
    return [nodo]

  # 2. CASO RECURSIVO: Si es una lista (una rama), aplicamos 'reduce'.
  # ¿Qué hace este reduce?
  #   - Toma una lista vacía inicial []
  #   - Aplica nuestra función recursiva a cada elemento interno
  #   - Concatena (+) los resultados puros.

  return reduce(lambda acumulado, elemento: acumulado + aplanar_arbol(elemento), nodo, [])

dataset_plano = aplanar_arbol(datos_anidados)

print("Datos originales (anidados) ", datos_anidados)
print("Datos procesados (planos) ", dataset_plano)



Datos originales (anidados)  [10, [20, 30], [[40]], 50, [60, [70, 80]]]
Datos procesados (planos)  [10, 20, 30, 40, 50, 60, 70, 80]


### Desglose de la Funcion

1. La Definición


```
def aplanar_arbol(nodo):
```

¿Por qué le llamamos nodo? En estructuras de datos, un "árbol" está hecho de ramas y hojas. A cualquier punto de ese árbol se le llama "nodo". Al usar esta palabra, le estamos diciendo a la mente que no sabemos si lo que nos acaba de llegar es una rama llena de cosas (lista) o una hoja final (número).

2. El Caso Base (El freno de mano)


```
 if not isinstance(nodo, list):
        return [nodo]
```
   
¿Qué hace isinstance?

Es el guardia de seguridad. Le pregunta al dato: "¿Tú eres de tipo lista?". El not invierte la pregunta: "¿Tú NO eres una lista?".

Si NO es una lista (ej. es el número 10): Significa que llegamos al fondo. Ya no hay más cajas que abrir.

EL TRUCO DE ORO (return [nodo]):

Fíjate que no devolvemos 10, devolvemos [10]. Lo metemos en una pequeña caja nueva. ¿Por qué? Porque más adelante vamos a usar el símbolo de suma (+) para unir todo. En Python, si intentas sumar una lista con un número ([] + 10), el programa explota. Si sumas dos listas ([] + [10]), Python las une perfectamente.

3. El Caso Recursivo (El Motor Principal)


```
 return reduce(lambda acumulado, elemento: acumulado + aplanar_arbol(elemento), nodo, [])
```
Aquí es donde la cabeza suele dar vueltas.

Vamos a desarmar este reduce en sus tres piezas fundamentales. reduce siempre necesita tres cosas:
1. Una función,
2. Los datos a recorrer
3. Un punto de partida.

Leyéndolo de derecha a izquierda (desde el final):

* (El punto de partida): Es nuestro carrito de compras vacío. Empezamos con una lista vacía donde iremos metiendo los números limpios.

* nodo (Los datos a recorrer): Es la caja grande que estamos abriendo en este momento.

* lambda acumulado, elemento: La función de orden superior. acumulado es el carrito de compras. elemento es la caja individual que acabamos de sacar del nodo.

### El Salto de Fe (La recursividad en acción):

```
acumulado + aplanar_arbol(elemento)
```

En lugar de simplemente meter el elemento al carrito, ¡volvemos a llamar a la máquina original (aplanar_arbol) y le lanzamos el elemento!

¿Por qué? Porque no sabemos si ese elemento es un 50 o un [60, [70, 80]].

Al llamar a aplanar_arbol(elemento), la máquina se encarga de resolver el misterio. Si es un 50, la máquina nos devolverá un [50]. Si es una caja compleja, la máquina se pausará, escarbará hasta el fondo y nos devolverá una lista plana con todo lo que encontró.

Finalmente, el + une lo que teníamos en el acumulado con la nueva listita plana que nos acaba de llegar.

### EL GRAN FINAL: Integración Total

Nuestro Pipeline funciona maravillosamente para un solo número. Pero, ¿recuerdan los JSON de la Clase 1? A veces los datos financieros vienen anidados como muñecas Matrioshkas: `[100, [200, -50], 300]`.

¡Nuestro pipeline no puede tragar listas anidadas! Necesitamos una **Máquina de Ingesta** que aplane esa lista antes de meterla a la fábrica. Aquí es donde usamos el `aplanar_arbol` recursivo que aprendimos.

In [ ]:
# ==========================================================
# PASO 3: LA MÁQUINA DE INGESTA (Aplanando árboles con reduce)
# ==========================================================
def aplanar_arbol(nodo):
    """
    Si encuentra una lista adentro de otra lista, usa la recursividad
    para extraer sus elementos y sumarlos a un carrito vacío ([]).
    """
    if type(nodo) is list:
        # Si es una lista, reduce escarba y suma las partes
        return reduce(lambda carrito, elemento: carrito + aplanar_arbol(elemento), nodo, [])
    else:
        # Caso Base: Si es un número normal, lo devuelve dentro de una lista
        return [nodo]

# ==========================================================
# ⚙️ EJECUCIÓN DEL SISTEMA COMPLETO ⚙️
# ==========================================================

# 1. Los datos crudos, sucios y anidados que llegaron de la API
datos_crudos_api = [100, [-20, 150], [200, [-50, 300]]]
print(f"1. Datos Crudos: {datos_crudos_api}")

# 2. Ingesta: Aplanamos los datos
datos_planos = aplanar_arbol(datos_crudos_api)
print(f"2. Datos Aplanados listos para procesar: {datos_planos}")

# 3. Pipeline: Pasamos todos los datos planos por nuestra fábrica
# (Usamos List Comprehension de la Clase 4 para procesar toda la lista)
reporte_final = [procesar_activo(precio) for precio in datos_planos]

print("\n📊 REPORTE FINANCIERO FINAL 📊")
for item in reporte_final:
    print(f" -> {item}")